version: "3"
services:
  spark-master:
    image: bde2020/spark-master:2.2.2-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:2.2.2-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
#  livy:
#    build:
#      context: ./livy
#      args:
#        - SPARK_MASTER=spark://spark-master:7077
#    tty: true
#    container_name: livy
#    depends_on:
#      - spark-master
#    ports:
#      - "8998:8998"
  mleap:
    build: ./mleap
    tty: true
    container_name: mleap
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
